version: '3'

services:
    app:
        build: .
        container_name: app
        volumes: 
            - .:/var/www
        networks: 
            - app-networks
        depends_on: 
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports: 
            - "8000:80"
        volumes:
            - .:/var/www
        networks: 
            - app-networks
        depends_on: 
            - app
        
    
    db:
        image: mysql:5.7
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports: 
            -   "33006:3306"
        volumes: 
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment: 
            -   MYSQL_ROOT_PASSWORD=root
            -   MYSQL_USER=root
        networks: 
            -   app-networks

    redis: 
        image: redis:alpine
        expose: 
            - 6379
        networks: 
            - app-networks

networks: 
    app-networks:
        driver: bridge